version: '3.9'

services:
  api:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - ${API_HOST_PORT}:4005
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}