version: '3.9'

services:
  api:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - ${API_HOST_PORT}:4005
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      -  mongodb-data:/data/db
    ports:
      - ${MONGO_HOST_PORT}:27017
volumes:
  mongodb-data: